runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|jpg))
  static_files: dist/\1
  upload: dist/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|jpg))
- url: /(.+)
  static_files: dist/index.html
  upload: dist/index.html
